name: Build U-Boot Android Bootimgs for sdm660 devices
on:
  #pull_request:
    #types: [opened, synchronize, reopened]
  push:
    branches:
      - v*-sdm660
    tags:
      - v*-sdm660
  workflow_dispatch:
jobs:
  build-downstream:
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: "qcom_defconfig qcom-sdm660-phone.config qcom-downstream.config"
      DEVICES: "bbry-luna bbry-athena"
      DTBS: "qcom/sdm636-bbry-luna-boe qcom/sdm660-bbry-athena-boe"
    steps:
      - name: Download apt packages
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu libgnutls28-dev xxd
      - name: Download mkbootimg
        run: |
          wget https://launchpadlibrarian.net/810765814/mkbootimg
          chmod +x mkbootimg
          sudo mv mkbootimg /usr/bin/mkbootimg
      - name: Checkout source from git
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
      - name: Run build script
        run: ./sdm660-build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: u-boot-sdm660-downstream
          path: binaries/
