on:
  workflow_call:
    inputs:
      DEFCONFIG:
        required: true
        type: string
      DEVICE:
        required: true
        type: string
      DTB:
        required: true
        type: string

jobs:
  build-bootimg:
    #runs-on: [self-hosted, Linux, X64, u-boot]
    runs-on: ubuntu-latest
    env:
      DEFCONFIG: ${{ inputs.DEFCONFIG }}
      DEVICE: ${{ inputs.DEVICE }}
      DTB: ${{ inputs.DTB }}
    steps:
      - name: Download apt packages
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu libgnutls28-dev
      - name: Download mkbootimg
        run: |
          wget https://launchpadlibrarian.net/810765814/mkbootimg
          chmod +x mkbootimg
          sudo mv mkbootimg /usr/bin/mkbootimg
      - name: Checkout source from git
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
      - name: Run build script
        run: |
          source ./common.sh
          build_uboot_android $DTB
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: u-boot-${{ inputs.DEVICE }}
          path: binaries/u-boot-${{ inputs.DEVICE }}.img
